version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=eventsProject
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-events:
    depends_on:
      - mysqldb
    image: raggadeya/alpine:1.0.0 # Updated with your image
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path": "/events",
        "server.port": "8089",
        "spring.mvc.format.date": "yyyy-MM-dd",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
        "logging.level.root": "info",
        "logging.pattern.console": "=%d{yyyy-MM-dd HH:mm:ss} -  %-5level- %logger{45} - %msg %n"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
